### ISSUE TITLE
Single-line Commands

### ISSUE THREAD

**Issue by Kapparina** [Kapparina/NicheTools#1]
Support for single-line command functionality (e.g.: "save key1" as command/parameter pair as an alternative to "save" as a command, followed by "key1" as the parameter used for the key name).

**Comment by Kapparina** [comment]
Feature implemented in commit [2c3dc83](https://github.com/Kapparina/NicheTools/commit/2c3dc83939ecb993244af581ea24b7b2bbdce55d).

**Comment by MrDwarf7** [comment]
Any ability to do this with "L key3" or "l key3" as well?

Will there be functionality/personability added in a later patch to add a type of breaker, IE: a pipe or a dash for these?

**Comment by Kapparina** [comment]
> Any ability to do this with "L key3" or "l key3" as well?
> 
> Will there be functionality/personability added in a later patch to add a type of breaker, IE: a pipe or a dash for these?

Case-insensitive commands... were working in a previous release, but appear to have broken! Thanks for flagging this - it will be fixed in an upcoming patch.
EDIT: Since fixed in [9df3c42](https://github.com/Kapparina/NicheTools/commit/9df3c42781f7048059d81288fc044e14e48a594e)

Regarding breakers (dashes/pipes etc.) - can you provide an example of how these would be used, as well as how these could serve as a beneficial addition to the application in its current state?

**Comment by Kapparina** [comment]
Since fixed in [9df3c42](https://github.com/Kapparina/NicheTools/commit/9df3c42781f7048059d81288fc044e14e48a594e)
