### ISSUE TITLE
Page implementation

### ISSUE THREAD

**Issue by MrDwarf7** [Kapparina/NicheTools#2]
The tool requires pages in order to format the data when calling "a" or "all" as it gets pushed off the screen when the list becomes larger than 10-25 items (Depending on screen size/cmd size)

**Comment by Kapparina** [comment]
A "lite" version of this functionality has been implemented in [f34575a](https://github.com/Kapparina/NicheTools/commit/f34575afc95e71f09758ffd14c80ed2d7f8c0082)

Future commits will iterate further upon this.
