### ISSUE TITLE
Ability to reference a "Key" value using the index number

### ISSUE THREAD

**Issue by MrDwarf7** [Kapparina/NicheTools#3]
Being able to access the "key" value by inputting the index number instead of the actual key would be really helpful - Sometimes can save things for later use, but the key I saved is really long and hard to type quickly if doing a lot of work into-/out-of the clipboard

**Comment by MrDwarf7** [comment]
Mentioned the potential issues with simply calling an index number during the programs "Save"/ "Load" area - 

"Hmm if I allow loading by index number I'll need to implement validation
 Else loading the value of index 1 where a key also exists named "1" could be problematic"
 
 There is a couple ways to fix this: 
Check for Int Types in that area/entry field - If it's an int type you can hop to a section of the code (Whether to skip or to handle it)
Or have a try/except block: so, by default it checks/forces for str:
(Could also invert this depending on your code)

If it throws a type error, due to being supplied an int, the except block can either handle it in a set of code (or function, depending on how large your project is) and transmute it, or you can have it hop to a section of code/function/section of the exception block that diverts it basically.


1. hard force a type for the value (Either TO the user, or IN the program)
IF ErrorType is V= do something 
    Elif: something = exception do E
Else: something = O do transmute to type of choice

2. Field that's being used on that "screen" doesn't even accept numbers and will tell the user to use a WORD specifically 
(Which is essentially just throwing an exception print() back)

3. Code it in such a way the input field on the "save"/"load" screen doesn't care, and have it done on the index/key side of things.
(For instance, index an internal value as bin value or something - Most humans won't use a bin value as a key, surely?)

4. You could "Validate" the requested creation of a key in a more rigid approach. 
Essentially matching it up against things in the index, allowing it if it isn't present, vs not if it is... But that will likely ask the program to loop through the entire keyset/array EVERY time the user requests to index something, leading to poor performance.

Alternative way to do it may be to create a Class and/or Method for handling the different value types.
Such as "save" vs. "load" vs the "internal index" vs. "Displayed Key" 

(Not that they all need to be separate. but doing comparisons against types you've created also allows more granular control over things.

**Comment by Kapparina** [comment]
Implemented in [f34575a](https://github.com/Kapparina/NicheTools/commit/f34575afc95e71f09758ffd14c80ed2d7f8c0082)

The solution utilised was to (for the time being) enforce a non-numerical (alpha-numerical or alphabetical) value for keys, as numbers are reserved for indexing purposes.

This feature will likely be revisited in the future following further testing and feedback.
