### ISSUE TITLE
Over-writing validation

### ISSUE THREAD

**Issue by MrDwarf7** [Kapparina/NicheTools#7]
If a key already exists the program needs to ask the user if they want to overwrite it before just "doing it" 
Preferably displaying the matching key just before the prompt so the user can see what it is they are overwriting.

Potentially have it show the existing key, and the key the person is trying to add.

(Feature addition of adding highlighting/underlining or something to compare the keys in the future???)

**Comment by Kapparina** [comment]
Added in commit [f34575a](https://github.com/Kapparina/NicheTools/commit/f34575afc95e71f09758ffd14c80ed2d7f8c0082)
